services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.mars  # Load environment variables from .env.mars
    environment:
      # API endpoints for client requests
      VITE_API_BASE: "${VITE_API_BASE}"
      VITE_AUDIT_API_BASE: "${VITE_AUDIT_API_BASE}"
      # API targets for Vite dev server proxy
      VITE_API_TARGET: "${VITE_API_TARGET}"
      VITE_AUDIT_API_TARGET: "${VITE_AUDIT_API_TARGET}"
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped