services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.mars  # Load environment variables from .env.mars
    environment:
      # Backend API URL for main API (/api/* proxying)
      VITE_API_TARGET: "${VITE_API_TARGET:-http://mars.butterflycluster.com:8080}"
      # Audit API URL for audit endpoints (/audit/* proxying)  
      VITE_AUDIT_API_TARGET: "${VITE_AUDIT_API_TARGET:-http://mars.butterflycluster.com:8081}"
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped