services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Point this at your backend. If your backend is reachable on the same host:
      #   http://mars.butterflycluster.com:8080
      # If your backend is another compose service (e.g., "backend:8080"), set that instead.
      BACKEND_BASE_URL: "http://192.168.1.218:8080"
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped