services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.mars  # Load environment variables from .env.mars
    environment:
      # API endpoints - needed at build time to be baked into the bundle
      VITE_API_BASE: "${VITE_API_BASE}"
      VITE_AUDIT_API_BASE: "${VITE_AUDIT_API_BASE}"
      VITE_USE_MOCK: "${VITE_USE_MOCK}"
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped